### ISSUE TITLE
Enable IPv6 by default

### ISSUE THREAD

**Issue by ffrediani** [extremeshok/docker-unbound#1]
Why do you have IPv6 disabled as default ? This is very contra-productive to IPv6 deployment which should always be default on any new software that is brought into production. That's why people should always have the mindset that only in case they don't have IPv6 available they should disable it optionally.
In the past IPv6 has been regarded as optional or accessory but not anymore.

**Comment by extremeshok** [comment]
ipv6 is enabled.

```
  do-ip4: yes
  do-udp: yes
  do-tcp: yes
  do-ip6: yes
  prefer-ip6: no
```
